[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
dotenvy = "0.15.7"
indoc = "2.0.5"
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["full"] }
